"""Pydantic schemas describing database records and API contracts."""

from .database import (
    Collection,
    Document,
    Element,
    Chat,
    Turn,
    TurnEvidence,
)
from .api import (
    CollectionCreate,
    CollectionUpdate,
    CollectionResponse,
    CollectionListResponse,
    DocumentUploadRequest,
    DocumentResponse,
    DocumentListResponse,
    IndexingRequest,
    IndexingResponse,
    ChatCreateRequest,
    ChatResponse,
    ChatListResponse,
    TurnSubmitRequest,
    TurnResponse,
    EvidenceListResponse,
    EvidenceAnchor,
)

__all__ = [
    "Collection",
    "Document",
    "Element",
    "Chat",
    "Turn",
    "TurnEvidence",
    "CollectionCreate",
    "CollectionUpdate",
    "CollectionResponse",
    "CollectionListResponse",
    "DocumentUploadRequest",
    "DocumentResponse",
    "DocumentListResponse",
    "IndexingRequest",
    "IndexingResponse",
    "ChatCreateRequest",
    "ChatResponse",
    "ChatListResponse",
    "TurnSubmitRequest",
    "TurnResponse",
    "EvidenceListResponse",
    "EvidenceAnchor",
]
