import argparse
import json
import math
from pathlib import Path
from typing import Iterable, List

import matplotlib.pyplot as plt


DEFAULT_FILES = [
    "/data2/jproject/OBQA/sample_data/test_convert/1-Cui et al. - 2019 - Class-Balanced Loss Based on Effective Number of Samples/auto/1-Cui et al. - 2019 - Class-Balanced Loss Based on Effective Number of Samples_content_list.json",
    "/data2/jproject/OBQA/sample_data/test_convert/4- ASHE 2021 National Conference/auto/4- ASHE 2021 National Conference_content_list.json",
]


def load_bbox_values(file_path: Path) -> List[List[int]]:
    with file_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return [entry["bbox"] for entry in data if "bbox" in entry]


def build_bins(values: Iterable[int], width: int) -> List[int]:
    min_val = min(values)
    max_val = max(values)
    start = width * math.floor(min_val / width)
    end = width * math.ceil((max_val + width) / width)
    return list(range(start, end + width, width))


def plot_histograms(values: List[List[int]], file_path: Path, output_dir: Path, bin_width: int) -> None:
    coordinate_series = list(zip(*values))
    coordinate_labels = ["Coordinate 1", "Coordinate 2", "Coordinate 3", "Coordinate 4"]
    output_dir.mkdir(parents=True, exist_ok=True)

    for index, coord_values in enumerate(coordinate_series):
        bins = build_bins(coord_values, bin_width)
        plt.figure(figsize=(8, 4))
        plt.hist(coord_values, bins=bins, edgecolor="black", label=coordinate_labels[index])
        plt.title(f"{file_path.name} - {coordinate_labels[index]} Distribution")
        plt.xlabel("Value Range")
        plt.ylabel("Frequency")
        plt.legend()
        safe_name = file_path.stem.replace(" ", "_").replace("/", "_")
        output_file = output_dir / f"{safe_name}_coord{index + 1}.png"
        plt.tight_layout()
        plt.savefig(output_file)
        plt.close()
        print(f"Saved histogram: {output_file}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot distribution histograms for each bbox coordinate extracted by MinerU."
    )
    parser.add_argument(
        "--files",
        nargs="+",
        default=DEFAULT_FILES,
        help="Content list JSON files generated by MinerU.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("scripts/output/bbox_histograms"),
        help="Directory to store histogram PNG files.",
    )
    parser.add_argument(
        "--bin-width",
        type=int,
        default=50,
        help="Value interval for the histogram bins.",
    )
    args = parser.parse_args()

    for file_str in args.files:
        file_path = Path(file_str)
        if not file_path.exists():
            print(f"Skipping missing file: {file_path}")
            continue
        bboxes = load_bbox_values(file_path)
        if not bboxes:
            print(f"No bbox data found in {file_path}")
            continue
        plot_histograms(bboxes, file_path, args.output_dir, args.bin_width)


if __name__ == "__main__":
    main()
